<?xml version="1.0"?>
<robot name="forklift" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find gazebo_rl_gym)/urdf/forklift/forklift_base.xacro" />

  <!-- Camera property definitions (keep from original model) -->
  <xacro:property name="r200_cam_rgb_px" value="0.005" />
  <xacro:property name="r200_cam_rgb_py" value="0.018" />
  <xacro:property name="r200_cam_rgb_pz" value="0.013" />
  <xacro:property name="r200_cam_depth_offset" value="0.01" />

  <!-- Base footprint as root - 必须有惯性参数才能让 Gazebo 正确计算速度 -->
  <link name="base_footprint">
    <inertial>
      <mass value="0.0001"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0"
              iyy="0.0001" iyz="0"
              izz="0.0001"/>
    </inertial>
  </link>

  <!-- Instantiate forklift base: front_axle + 4 wheels -->
  <xacro:forklift_base parent_link="base_footprint" />

  <!-- IMU link on main chassis (front_axle) -->
  <joint name="imu_joint" type="fixed">
    <parent link="front_axle" />
    <child link="imu_link" />
    <origin xyz="0.0 0 0.068" rpy="0 0 0" />
  </joint>
  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0"
              iyy="0.0001" iyz="0"
              izz="0.0001"/>
    </inertial>
  </link>

  <!-- 2D lidar on chassis -->
  <joint name="scan_joint" type="fixed">
    <parent link="front_axle" />
    <child link="base_scan" />
    <origin xyz="-0.35 0 0.65" rpy="0 0 0" />
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://gazebo_rl_gym/meshes/turtlebot3/sensors/lds.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="dark" />
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0" />
      <geometry>
        <cylinder length="0.0315" radius="0.055" />
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <!-- Realsense camera on chassis -->
  <joint name="camera_joint" type="fixed">
    <origin xyz="0.064 -0.065 0.5" rpy="0 0 0" />
    <parent link="front_axle" />
    <child link="camera_link" />
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 1.57" />
      <geometry>
        <mesh filename="package://gazebo_rl_gym/meshes/turtlebot3/sensors/r200.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0" />
      <geometry>
        <box size="0.012 0.132 0.020" />
      </geometry>
    </collision>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0" />
    <parent link="camera_link" />
    <child link="camera_rgb_frame" />
  </joint>
  <link name="camera_rgb_frame" />

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57" />
    <parent link="camera_rgb_frame" />
    <child link="camera_rgb_optical_frame" />
  </joint>
  <link name="camera_rgb_optical_frame" />

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0" />
    <parent link="camera_link" />
    <child link="camera_depth_frame" />
  </joint>
  <link name="camera_depth_frame" />

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57" />
    <parent link="camera_depth_frame" />
    <child link="camera_depth_optical_frame" />
  </joint>
  <link name="camera_depth_optical_frame" />

</robot>
